name: 'Docker build and push'
description: 'Simple Docker build and push action'
author: devops@zilliqa.com

inputs:
  file:
    description: 'The path to the Dockerfile. If not set, it is uses the context path.'
    required: false
  context:
    description: 'The context to build the Dockerfile'
    required: true
  build-args:
    description: 'Arguments to build the image'
    required: false
  pull:
    description: 'Enable/disable image pull'
    required: false
    default: true
  push:
    description: 'Enable/disable image push'
    required: false
    default: true
  target:
    description: 'The target to build in the image'
    required: false
  tags:
    description: 'The tags of the image'
    required: true
  cache-from:
    description: 'Docker registry'
    required: false
  cache-to:
    description: 'The username to access the registry'
    required: false
  secrets:
    description: "List of secrets to expose to the build (e.g., key=string, GIT_AUTH_TOKEN=mytoken)"
    required: false

outputs:
  imageid:
    description: 'Image ID'
    value: ${{ steps.build-push.outputs.imageid }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build-push.outputs.digest }}
  metadata:
    description: 'Build result metadata'
    value: ${{ steps.build-push.outputs.metadata }}

runs:
  using: "composite"
  steps:
  - name: Set up QEMU
    uses: docker/setup-qemu-action@v2
  - name: Set up Docker Context for Buildx
    shell: bash
    id: buildx-context
    run: |
      docker context create buildx-context || true 
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
    with:
      endpoint: buildx-context
  - name: Build and push Docker images
    id: build-push
    uses: docker/@v5
    with:
      file: ${{ inputs.file }}
      context: ${{ inputs.context }}
      build-args: ${{ inputs.build-args }}
      pull: ${{ inputs.pull }}
      push: ${{ inputs.push }}
      target: ${{ inputs.target }}
      tags: ${{ inputs.tags }}
      cache-from: ${{ inputs.cache-from }}
      cache-to: ${{ inputs.cache-to }}
      secrets: ${{ inputs.secrets }}