name: 'Generate tag'
description: 'Action to generate a tag from git commit sha'
author: devops@zilliqa.com

inputs:
  tag:
    description: 'Input tag'
    required: true
  length:
    description: 'The number of chars composing the tag'
    required: false
    default: 7
  latest:
    description: 'If true add the tag latest'
    required: false
    default: false
outputs:
  tags:
    description: "Generated tag"
    value: ${{ steps.build-tag.outputs.tag }}

runs:
  using: "composite"
  steps:
  - name: Split image and tag
    id: split-image-and-tag
    run: |
      IFS=':'
      read -ra ADDR <<< "${{ inputs.tag }}"
      echo "image=${ADDR[0]}" >> $GITHUB_OUTPUT
      echo "tag=${ADDR[1]}" >> $GITHUB_OUTPUT
    shell: bash
  - name: Get image tag from git commit
    id: set-tag
    run: |
      if [ "${{ steps.split-image-and-tag.outputs.tag }}" = "" ]; then
        echo "tag=$(git rev-parse --short=${{ inputs.length }} HEAD)" >> $GITHUB_OUTPUT
      else
        echo "tag=${{ steps.split-image-and-tag.outputs.tag }}" >> $GITHUB_OUTPUT
      fi
    shell: bash
  - name: Build tag
    id: build-tag
    run: |
      if [ "${{ inputs.latest }}" = true ]; then
        echo "tag=${{ steps.split-image-and-tag.outputs.image }}:${{ steps.set-tag.outputs.tag }},${{ steps.split-image-and-tag.outputs.image }}:latest" >> $GITHUB_OUTPUT
      else
        echo "tag=${{ steps.split-image-and-tag.outputs.image }}:${{ steps.set-tag.outputs.tag }}" >> $GITHUB_OUTPUT
      fi
    shell: bash