name: 'Docker cache'
description: 'Docker cache setup action'
author: devops@zilliqa.com

inputs:
  key:
    description: 'The key to store/retrieve the cache'
    required: true

outputs:
  cachefrom:
    description: 'Docker layers Cache from value'
    value: ${{ steps.cache.outputs.cachefrom }}
  cacheto:
    description: 'Docker layers Cache to value'
    value: ${{ steps.cache.outputs.cacheto }}

runs:
  using: "composite"
  steps:
  - name: Set cache
    id: cache
    run: |
      if [ "${{ inputs.key }}" = "" ]; then
        echo "cachefrom=" >> $GITHUB_OUTPUT
        echo "cacheto=" >> $GITHUB_OUTPUT
      else
        echo "cachefrom=type=gha,scope=${{ github.event.repository.name }}-${{ inputs.key }}" >> $GITHUB_OUTPUT
        echo "cacheto=type=gha,scope=${{ github.event.repository.name }}-${{ inputs.key }},mode=max" >> $GITHUB_OUTPUT
      fi
    shell: bash