name: Format README.md

on:
  push:
    # branches:
      # - main

jobs:
  sync-assets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [configure-aws-credentials, configure-aws-profile, docker-build-push, docker-cache]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run auto-doc
        uses: tj-actions/auto-doc@v1
        with:
          action: "actions/${{ matrix.path }}/action.yml"
          output: "actions/${{ matrix.path }}/README.md"

      - name: Run remark
        uses: tj-actions/remark@v3
        with:
          files: |
            actions/${{ matrix.path }}/README.md

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v13
        id: verify_changed_files
        with:
          files: |
            actions/${{ matrix.path }}/README.md

      - name: README.md changed
        if: steps.verify_changed_files.outputs.files_changed == 'true'
        run: |
          echo "README.md has uncommitted changes"
          exit 1
      
      - name: Create Pull Request
        if: failure()
        uses: peter-evans/create-pull-request@v4
        with:
          base: "doc"
          labels: "merge when passing"
          title: "Updated ${{ matrix.path }}/README.md"
          branch: "chore/update-readme/${{ matrix.path }}"
          commit-message: "Updated ${{ matrix.path }}/README.md"
          body: "Updated README.md"
          token: ${{ secrets.PAT_TOKEN }}
