name: Test - Versioning

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '**.md'

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
