name: Test - CI Dockerized app build and push

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '**.md'

actions-tagger:
  runs-on: ubuntu-latest
  steps:
    - uses: Actions-R-Us/actions-tagger@latest
      with:
        publish_latest_tag: true